### ISSUE TITLE
TODO:code cleanup

### ISSUE THREAD

**Issue by ghost** [Sysca11/bdlauncher#55]
- [ ] Separate old version db compatible code from main.cpp
- [ ] use api with namespace,like Base::sendNetworkPkt,BDLEvent::register_xxx
- [ ] use eventClass for event listeners.
- [ ] rewrite c-style codes to cpp-style.
