### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by ghost** [Sysca11/bdlauncher#76]
- [ ] Fix max_homes #75 
- [ ] XUID-based money system #57 
- [ ] Event system
- [ ] Automatic ban in anticheat
- [ ] runtime reflection helper for ServerPlayer
